/*
 * FulfilmentFactoriesType.java
 *
 * This work is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This work is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA
 *
 * Copyright (c) 2010-2016 iTransformers Labs. All rights reserved.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.02 at 04:28:40 PM EEST 
//


package net.itransformers.topologyviewer.fulfilmentfactory.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fulfilment-factoriesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fulfilment-factoriesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fulfilment-factory-types" type="{}fulfilment-factory-typesType"/>
 *         &lt;element name="fulfilment-factory" type="{}fulfilment-factoryType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fulfilment-factoriesType", propOrder = {
    "fulfilmentFactoryTypes",
    "fulfilmentFactory"
})
public class FulfilmentFactoriesType {

    @XmlElement(name = "fulfilment-factory-types", required = true)
    protected FulfilmentFactoryTypesType fulfilmentFactoryTypes;
    @XmlElement(name = "fulfilment-factory")
    protected List<FulfilmentFactoryType> fulfilmentFactory;

    /**
     * Gets the value of the fulfilmentFactoryTypes property.
     * 
     * @return
     *     possible object is
     *     {@link FulfilmentFactoryTypesType }
     *     
     */
    public FulfilmentFactoryTypesType getFulfilmentFactoryTypes() {
        return fulfilmentFactoryTypes;
    }

    /**
     * Sets the value of the fulfilmentFactoryTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link FulfilmentFactoryTypesType }
     *     
     */
    public void setFulfilmentFactoryTypes(FulfilmentFactoryTypesType value) {
        this.fulfilmentFactoryTypes = value;
    }

    /**
     * Gets the value of the fulfilmentFactory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fulfilmentFactory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFulfilmentFactory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FulfilmentFactoryType }
     * 
     * 
     */
    public List<FulfilmentFactoryType> getFulfilmentFactory() {
        if (fulfilmentFactory == null) {
            fulfilmentFactory = new ArrayList<FulfilmentFactoryType>();
        }
        return this.fulfilmentFactory;
    }

}
