/*
 * ObjectFactory.java
 *
 * This work is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License,
 * or (at your option) any later version.
 *
 * This work is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA
 *
 * Copyright (c) 2010-2016 iTransformers Labs. All rights reserved.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 05:12:40 AM EST 
//


package net.itransformers.topologyviewer.fulfilmentfactory.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.itransformers.topologyviewer.fulfilmentfactory.config package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FulfilmentFactories_QNAME = new QName("", "fulfilment-factories");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.itransformers.topologyviewer.fulfilmentfactory.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FulfilmentFactoriesType }
     * 
     */
    public FulfilmentFactoriesType createFulfilmentFactoriesType() {
        return new FulfilmentFactoriesType();
    }

    /**
     * Create an instance of {@link TypeType }
     * 
     */
    public TypeType createTypeType() {
        return new TypeType();
    }

    /**
     * Create an instance of {@link FulfilmentFactoryTypesType }
     * 
     */
    public FulfilmentFactoryTypesType createFulfilmentFactoryTypesType() {
        return new FulfilmentFactoryTypesType();
    }

    /**
     * Create an instance of {@link FulfilmentFactoryType }
     * 
     */
    public FulfilmentFactoryType createFulfilmentFactoryType() {
        return new FulfilmentFactoryType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FulfilmentFactoriesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fulfilment-factories")
    public JAXBElement<FulfilmentFactoriesType> createFulfilmentFactories(FulfilmentFactoriesType value) {
        return new JAXBElement<FulfilmentFactoriesType>(_FulfilmentFactories_QNAME, FulfilmentFactoriesType.class, null, value);
    }

}
