//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.27 at 10:58:14 PM EET 
//


package net.itransformers.postDiscoverer.reportGenerator;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for commandDescriptorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="commandDescriptorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="login-script" type="{}login-scriptType" minOccurs="0"/>
 *         &lt;element name="logout-script" type="{}logout-scriptType" minOccurs="0"/>
 *         &lt;element name="send-command-script" type="{}send-command-scriptType"/>
 *         &lt;element name="command" type="{}commandType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="deviceType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="deviceName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "commandDescriptorType", propOrder = {
    "loginScript",
    "logoutScript",
    "sendCommandScript",
    "command"
})
public class CommandDescriptorType {

    @XmlElement(name = "login-script")
    protected LoginScriptType loginScript;
    @XmlElement(name = "logout-script")
    protected LogoutScriptType logoutScript;
    @XmlElement(name = "send-command-script", required = true)
    protected SendCommandScriptType sendCommandScript;
    protected List<CommandType> command;
    @XmlAttribute(name = "deviceType")
    protected String deviceType;
    @XmlAttribute(name = "deviceName")
    protected String deviceName;

    /**
     * Gets the value of the loginScript property.
     * 
     * @return
     *     possible object is
     *     {@link LoginScriptType }
     *     
     */
    public LoginScriptType getLoginScript() {
        return loginScript;
    }

    /**
     * Sets the value of the loginScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoginScriptType }
     *     
     */
    public void setLoginScript(LoginScriptType value) {
        this.loginScript = value;
    }

    /**
     * Gets the value of the logoutScript property.
     * 
     * @return
     *     possible object is
     *     {@link LogoutScriptType }
     *     
     */
    public LogoutScriptType getLogoutScript() {
        return logoutScript;
    }

    /**
     * Sets the value of the logoutScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogoutScriptType }
     *     
     */
    public void setLogoutScript(LogoutScriptType value) {
        this.logoutScript = value;
    }

    /**
     * Gets the value of the sendCommandScript property.
     * 
     * @return
     *     possible object is
     *     {@link SendCommandScriptType }
     *     
     */
    public SendCommandScriptType getSendCommandScript() {
        return sendCommandScript;
    }

    /**
     * Sets the value of the sendCommandScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendCommandScriptType }
     *     
     */
    public void setSendCommandScript(SendCommandScriptType value) {
        this.sendCommandScript = value;
    }

    /**
     * Gets the value of the command property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the command property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommandType }
     * 
     * 
     */
    public List<CommandType> getCommand() {
        if (command == null) {
            command = new ArrayList<CommandType>();
        }
        return this.command;
    }

    /**
     * Gets the value of the deviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * Sets the value of the deviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceType(String value) {
        this.deviceType = value;
    }

    /**
     * Gets the value of the deviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * Sets the value of the deviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceName(String value) {
        this.deviceName = value;
    }

}
