//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.27 at 10:58:14 PM EET 
//


package net.itransformers.postDiscoverer.reportGenerator;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for report-generatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="report-generatorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="report-entry" type="{}report-entryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="commandDescriptor" type="{}commandDescriptorType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "report-generatorType", propOrder = {
    "reportEntry",
    "commandDescriptor"
})
public class ReportGeneratorType {

    @XmlElement(name = "report-entry")
    protected List<ReportEntryType> reportEntry;
    protected List<CommandDescriptorType> commandDescriptor;

    /**
     * Gets the value of the reportEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportEntryType }
     * 
     * 
     */
    public List<ReportEntryType> getReportEntry() {
        if (reportEntry == null) {
            reportEntry = new ArrayList<ReportEntryType>();
        }
        return this.reportEntry;
    }

    /**
     * Gets the value of the commandDescriptor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commandDescriptor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommandDescriptor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommandDescriptorType }
     * 
     * 
     */
    public List<CommandDescriptorType> getCommandDescriptor() {
        if (commandDescriptor == null) {
            commandDescriptor = new ArrayList<CommandDescriptorType>();
        }
        return this.commandDescriptor;
    }

}
