/* Generated by Together */

public class businessConstraint {
    public businessConstraint(String value, String name) {
        id = id++;
        value = value;
        name = name;
    }

    private long id = 1;

    long Create();

    long Delete();

    long Modify();

    private String value;
    private String name;

    /**
     * @supplierCardinality 1..*
     * @link aggregationByValue
     */
    private Parameter lnkparameter;
}
