/* Generated by Together */

public class effect {
    public effect(long id, String value, String name, int param) {
        id = id;
        value = value;
        name = name;
    }

    long Create();

    long Delete();

    long Modify();

    private long id;
    private String value;
    private String name;

    /**
     * @supplierCardinality 1..*
     * @link aggregationByValue
     */
    private Parameter lnkparameter;
}
