/* Generated by Together */

public class Parameter {
    public Parameter(long id,String name, String value) {
        this.id=id;
        this.name = name;
        this.value = value;
    }

    public long DeletebyId(long id);

    public long ModifbyIdy(long id, String name, String value);

    private String value;
    private String name;
    private long id;
}
