/* Generated by Together */

public class step {
    public step(long id, String value, String name, int param) {
        id = id;
        value = value;
        name = name;
    }

    private long id;
    private String value;
    private String name;

    /**
     * @clientCardinality 1..*
     * @link aggregationByValue
     */
    private businessConstraint lnkbusinessConstraint;

    /**
     * @link aggregationByValue
     * @clientCardinality 1..*
     */
    private techConstraint lnktechConstraint;

    /**
     * @link aggregationByValue
     * @clientCardinality 1..*
     */
    private effect lnkeffect;

    long Create();

    long Delete();

    long Modify();
}
