/* Generated by Together */

public class strategy {
    public strategy(long id, String value, String name, int param) {
        id = id;
        value = value;
        name = name;
    }

    long AddStep();

    long DeleteStep();

    long ModifyStepOrder();

    private String value;
    private String name;
    private long id;

    /**
     * @clientCardinality 0..*
     * @link aggregationByValue
     */
    private List<step> lnkstep;
}
