/* Generated by Together */

public class techConstraint {
    public techConstraint(long id, String value, String name) {
        value = value;
        name = name;
    }

    private long id;
    private String value;
    private String name;

    long Create();

    long Delete();

    long Modify();

    /**
     * @supplierCardinality 1..*
     * @link aggregationByValue
     */
    private Parameter lnkparameter;
}
