
package net.itransformers.ws.upload;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TreeImporterImplService", targetNamespace = "http://upload.ws.itransformers.net/", wsdlLocation = "http://localhost:8080/wsitransformer-0.1-SNAPSHOT/upload?wsdl")
public class TreeImporterImplService
    extends Service
{

    private final static URL TREEIMPORTERIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.itransformers.ws.upload.TreeImporterImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.itransformers.ws.upload.TreeImporterImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/wsitransformer-0.1-SNAPSHOT/upload?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/wsitransformer-0.1-SNAPSHOT/upload?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TREEIMPORTERIMPLSERVICE_WSDL_LOCATION = url;
    }

    public TreeImporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TreeImporterImplService() {
        super(TREEIMPORTERIMPLSERVICE_WSDL_LOCATION, new QName("http://upload.ws.itransformers.net/", "TreeImporterImplService"));
    }

    /**
     * 
     * @return
     *     returns TreeImporter
     */
    @WebEndpoint(name = "TreeImporterImplPort")
    public TreeImporter getTreeImporterImplPort() {
        return super.getPort(new QName("http://upload.ws.itransformers.net/", "TreeImporterImplPort"), TreeImporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TreeImporter
     */
    @WebEndpoint(name = "TreeImporterImplPort")
    public TreeImporter getTreeImporterImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://upload.ws.itransformers.net/", "TreeImporterImplPort"), TreeImporter.class, features);
    }

}
