
package net.itransformers.ws.upload;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TreeImporter", targetNamespace = "http://upload.ws.itransformers.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TreeImporter {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Long
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "importNode", targetNamespace = "http://upload.ws.itransformers.net/", className = "net.itransformers.ws.upload.ImportNode")
    @ResponseWrapper(localName = "importNodeResponse", targetNamespace = "http://upload.ws.itransformers.net/", className = "net.itransformers.ws.upload.ImportNodeResponse")
    public Long importNode(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Node arg1)
        throws Exception_Exception
    ;

}
